using System.Text;
using System.Text.Json;

namespace Server.Services;

public class GeminiService : IGeminiService
{
    private readonly HttpClient _httpClient;
    private readonly IConfiguration _configuration;
    private readonly ILogger<GeminiService> _logger;

    public GeminiService(
        HttpClient httpClient,
        IConfiguration configuration,
        ILogger<GeminiService> logger
    )
    {
        _httpClient = httpClient;
        _configuration = configuration;
        _logger = logger;
    }

    public async Task<List<string>> GenerateImagesAsync(string prompt, int count = 2)
    {
        var apiKey =
            _configuration["Gemini:ApiKey"]
            ?? throw new InvalidOperationException("Gemini API key not configured");

        var apiUrl =
            _configuration["Gemini:ApiUrl"]
            ?? "https://generativelanguage.googleapis.com/v1beta/models/imagen-3.0-generate-001:predict";

        try
        {
            var requestBody = new
            {
                instances = new[] { new { prompt } },
                parameters = new { sampleCount = count },
            };

            var jsonContent = JsonSerializer.Serialize(requestBody);
            var content = new StringContent(jsonContent, Encoding.UTF8, "application/json");

            _httpClient.DefaultRequestHeaders.Clear();
            _httpClient.DefaultRequestHeaders.Add("Authorization", $"Bearer {apiKey}");

            var response = await _httpClient.PostAsync(apiUrl, content);

            if (!response.IsSuccessStatusCode)
            {
                var errorContent = await response.Content.ReadAsStringAsync();
                _logger.LogError(
                    "Gemini API error: {StatusCode} - {Error}",
                    response.StatusCode,
                    errorContent
                );
                throw new HttpRequestException($"Gemini API returned {response.StatusCode}");
            }

            var responseContent = await response.Content.ReadAsStringAsync();
            var result = JsonSerializer.Deserialize<GeminiResponse>(responseContent);

            if (result?.Predictions == null || result.Predictions.Count == 0)
            {
                throw new InvalidOperationException("No images generated by Gemini API");
            }

            // Extract base64 images from predictions
            var images = result
                .Predictions.Where(p => !string.IsNullOrEmpty(p.BytesBase64Encoded))
                .Select(p => $"data:image/png;base64,{p.BytesBase64Encoded}")
                .ToList();

            if (images.Count == 0)
            {
                throw new InvalidOperationException("No valid images in Gemini API response");
            }

            return images;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error generating images with Gemini API");
            throw;
        }
    }

    private class GeminiResponse
    {
        public List<Prediction> Predictions { get; set; } = new();
    }

    private class Prediction
    {
        public string BytesBase64Encoded { get; set; } = string.Empty;
    }
}
