using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Server.Services;

public class GeminiService : IGeminiService
{
    private readonly HttpClient _httpClient;
    private readonly IConfiguration _configuration;
    private readonly ILogger<GeminiService> _logger;

    public GeminiService(
        HttpClient httpClient,
        IConfiguration configuration,
        ILogger<GeminiService> logger
    )
    {
        _httpClient = httpClient;
        _configuration = configuration;
        _logger = logger;
    }

    public async Task<List<string>> GenerateImagesAsync(string prompt, int count = 2)
    {
        return await GenerateImagesAsync(prompt, null, count);
    }

    public async Task<List<string>> GenerateImagesAsync(
        string prompt,
        string? base64Image = null,
        int count = 2
    )
    {
        var apiKey =
            _configuration["Gemini:ApiKey"]
            ?? throw new InvalidOperationException("Gemini API key not configured");

        var apiUrl =
            _configuration["Gemini:ApiUrl"]
            ?? "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-image:generateContent";

        try
        {
            // Build the parts array
            var parts = new List<object> { new { text = prompt } };

            // Add image if provided
            if (!string.IsNullOrEmpty(base64Image))
            {
                // Remove data URI prefix if present
                var imageData = base64Image;
                if (imageData.Contains(","))
                {
                    imageData = imageData.Split(',')[1];
                }

                // Determine MIME type from data URI or default to jpeg
                var mimeType = "image/jpeg";
                if (base64Image.StartsWith("data:"))
                {
                    var mimeMatch = base64Image.Substring(5, base64Image.IndexOf(';') - 5);
                    if (!string.IsNullOrEmpty(mimeMatch))
                    {
                        mimeType = mimeMatch;
                    }
                }

                parts.Add(new { inline_data = new { mime_type = mimeType, data = imageData } });
            }

            var requestBody = new
            {
                contents = new[] { new { parts } },
                generationConfig = new { imageConfig = new { aspectRatio = "16:9" } },
            };

            var jsonContent = JsonSerializer.Serialize(requestBody);
            var content = new StringContent(jsonContent, Encoding.UTF8, "application/json");

            _httpClient.DefaultRequestHeaders.Clear();
            _httpClient.DefaultRequestHeaders.Add("x-goog-api-key", apiKey);

            var response = await _httpClient.PostAsync(apiUrl, content);

            if (!response.IsSuccessStatusCode)
            {
                var errorContent = await response.Content.ReadAsStringAsync();
                _logger.LogError(
                    "Gemini API error: {StatusCode} - {Error}",
                    response.StatusCode,
                    errorContent
                );
                throw new HttpRequestException($"Gemini API returned {response.StatusCode}");
            }

            var responseContent = await response.Content.ReadAsStringAsync();
            _logger.LogInformation("Gemini API response: {Response}", responseContent);

            var result = JsonSerializer.Deserialize<GeminiFlashImageResponse>(
                responseContent,
                new JsonSerializerOptions { PropertyNameCaseInsensitive = true }
            );

            if (result?.Candidates == null || result.Candidates.Count == 0)
            {
                throw new InvalidOperationException("No images generated by Gemini API");
            }

            // Extract base64 images from candidates
            var images = new List<string>();
            foreach (var candidate in result.Candidates)
            {
                if (candidate.Content?.Parts != null)
                {
                    foreach (var part in candidate.Content.Parts)
                    {
                        if (part.InlineData != null && !string.IsNullOrEmpty(part.InlineData.Data))
                        {
                            var mimeType = part.InlineData.MimeType ?? "image/png";
                            images.Add($"data:{mimeType};base64,{part.InlineData.Data}");
                        }
                    }
                }
            }

            if (images.Count == 0)
            {
                throw new InvalidOperationException("No valid images in Gemini API response");
            }

            return images;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error generating images with Gemini API");
            throw;
        }
    }

    // Response models for Gemini 2.5 Flash Image API
    private class GeminiFlashImageResponse
    {
        [JsonPropertyName("candidates")]
        public List<Candidate> Candidates { get; set; } = new();
    }

    private class Candidate
    {
        [JsonPropertyName("content")]
        public Content? Content { get; set; }

        [JsonPropertyName("finishReason")]
        public string? FinishReason { get; set; }
    }

    private class Content
    {
        [JsonPropertyName("parts")]
        public List<Part> Parts { get; set; } = new();

        [JsonPropertyName("role")]
        public string? Role { get; set; }
    }

    private class Part
    {
        [JsonPropertyName("text")]
        public string? Text { get; set; }

        [JsonPropertyName("inlineData")]
        public InlineData? InlineData { get; set; }
    }

    private class InlineData
    {
        [JsonPropertyName("mimeType")]
        public string? MimeType { get; set; }

        [JsonPropertyName("data")]
        public string? Data { get; set; }
    }
}
